name: Sanity test
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write 

jobs:
  test_model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: action/setup-python@v4
        with:
          python-versions: "3.9"
      - uses: iterative/setup-cml@v2
      - name : run unit tests
        run: |
          pip install -r requirements.txt
          python -m test 2>&1 > test_output.txt
      - name: Create CML report
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "test output" > report.md
          echo "\'\'\'" >> report.md
          cat test_output.txt >> report.md
          echo "\'\'\'" > report.md
          echo "metrics from training" >> report.md
          cat metrics.csv >> report.md
          cml comment create --publish report.md
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Install any other project dependencies from requirements.txt
        # pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest
